name: Debug deploy chrome extension

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'    

jobs:
  build:
    name: Build chrome extension
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build:prod

    - name: Upload Release Build Artifact
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: chrome
        path: dist

  deploy:
    name: Deploy chrome extension
    needs: build
    runs-on: ubuntu-latest
#    if: false ##

    steps:
    - name: Download artifact
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        name: chrome
        path: chrome

    - name: ls -l
      run: ls -l && cd chrome/ && ls -l && cd ../

    - name: Check dep
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const script = require('./.github/workflows/scripts/js/check-versions.js')
          const result = await script();
          return result;

#    - run: npx chrome-webstore-upload-cli@3
#      working-directory: dist/
#      env:
#        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
#        CLIENT_ID: ${{ secrets.CLIENT_ID }}
#        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
